### ISSUE TITLE
Daily quest problem

### ISSUE THREAD

**Issue by hiperesp** [hiperesp/DragonFable-Private-Server#59]
Invalid return when we do the daily quest
![Screenshot_20241008_035615_Chrome.jpg](https://github.com/user-attachments/assets/974a1bb7-336e-4565-99f1-c561383d363e)

**Comment by hiperesp** [comment]
![Screenshot_20241008_040111_Chrome.jpg](https://github.com/user-attachments/assets/7b56b581-a737-4354-a576-5052d96900d2)

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method hiperesp\server\vo\CharacterVO::getDailyQuestAvailable() in /var/www/html/server-emulator/hiperesp/server/models/CharacterModel.php:120
Stack trace:
#0 /var/www/html/server-emulator/hiperesp/server/controllers/QuestController.php(68): hiperesp\server\models\CharacterModel->applyQuestRewards(Object(hiperesp\server\vo\CharacterVO), Object(hiperesp\server\vo\QuestVO), Array)
#1 /var/www/html/server-emulator/hiperesp/server/controllers/Controller.php(95): hiperesp\server\controllers\QuestController->complete_mar2011(Object(SimpleXMLElement))
#2 [internal function]: hiperesp\server\controllers\Controller::entry(Object(ReflectionMethod))
#3 /var/www/html/server-emulator/includes/boot.php(10): ReflectionMethod->invoke(NULL, '/cf-questcomple...')
#4 /var/www/html/server-emulator/server.php(5): include('/var/www/html/s...')
#5 {main}
  thrown in <b>/var/www/html/server-emulator/hiperesp/server/models/CharacterModel.php</b> on line <b>120</b><br />
```

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method hiperesp\server\vo\CharacterVO::getDailyQuestAvailable() in /var/www/html/server-emulator/hiperesp/server/models/CharacterModel.php:120
Stack trace:
#0 /var/www/html/server-emulator/hiperesp/server/controllers/QuestController.php(68): hiperesp\server\models\CharacterModel->applyQuestRewards(Object(hiperesp\server\vo\CharacterVO), Object(hiperesp\server\vo\QuestVO), Array)
#1 /var/www/html/server-emulator/hiperesp/server/controllers/Controller.php(95): hiperesp\server\controllers\QuestController->complete_mar2011(Object(SimpleXMLElement))
#2 [internal function]: hiperesp\server\controllers\Controller::entry(Object(ReflectionMethod))
#3 /var/www/html/server-emulator/includes/boot.php(10): ReflectionMethod->invoke(NULL, '/cf-questcomple...')
#4 /var/www/html/server-emulator/server.php(5): include('/var/www/html/s...')
#5 {main}
  thrown in <b>/var/www/html/server-emulator/hiperesp/server/models/CharacterModel.php</b> on line <b>120</b><br />
